[ Geth로 프라이빗 노드 구축 III (Geth 콘솔) ]

(채굴 진행중..)

0:10 | 백그라운드로 돌고 있는 노드에 연결시켜서 자바스크립트 콘솔로 보여주는 작업

    geth attach ipc:\\.\pipe\geth.ipc 입력.
    오류발생 : Fatal: Unable to attach to remote geth: dial unix \.pipegeth.ipc: connect: no such file or directory
    오류해결 : geth attach ipc:geth.ipc  이렇게 입력하니까 됨. 입력방식이 다른 듯(업그레이드가 된건지, 맥과 윈도우의 차인지..). 

1:15 | 콘솔정보확인

    eth.coinbase - 코인베이스계정. 제일 첫번째로 만들었던 계정. 0x0906ad8642cfcc68ecd1bd394acb64d3ddac8dd2
    (ex coinbase: 0x0906ad8642cfcc68ecd1bd394acb64d3ddac8dd2)
    modules - 해당 창에서 쓸 수 있는 api를 나열한 것. nodestart.cmd 파일을 만들었을 때 파라미터로 http.api를, 값으로 eth,web3,personal,net를 주었음. 해당 api들을 콘솔에서 사용가능.
    (ex modules: admin:1.0 debug:1.0 eth:1.0 ethash:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0)
    
    [ ether api 명령어 ]
    ? eth.coinbase - 코인베이스 계정(첫번째로 만들었던 계정).
    ? eth.accounts - 현재 이 노드에 등록된 모든 계정들이 나옴.
    ? eth.getBalance(계정)- 계정에 에더가 얼마나 들어가있는지 알려줌. 
    ex) eth.getBalance(eth.accounts[1]) = 두번째 계정의 에더
    > eth.getBalance(eth.accounts[0])
    674000000000000000000 - 강의처럼 wei로 변환해서 보여주지는 않네..
    * wei : 에더를 나타내는 가장 작은 단위

    wei를 에더로 변환해서 값을 보는 방법 - web3 api의 fromWei함수를 사용할 수 있음.
    [ web3 api 명령어 ]
    ? web3.fromWei() - 어떤 wei 값도 ether로 변환해 보여준다. https://web3js.readthedocs.io/en/v1.2.11/web3-utils.html
    ex) > web3.fromWei(eth.getBalance(eth.coinbase), "ether")
        744

    [miner api 명령어]
    ? miner.stop() - 채굴을 멈추는 명령어.
    오류 발생 - 'miner.stop()' 입력시 'null'
    해결시도 - 어느 순간 채굴이 멈춤. miner.stop()은 계속 'null' 값만 나옴
INFO [07-05|16:12:32.614] ? mined potential block                  number=405 hash=e641b4..7c9ebe
INFO [07-05|16:12:32.614] Commit new mining work                   number=406 sealhash=3be0fa..d50507 uncles=0 txs=0 gas=0 fees=0 elapsed="321.208?s"
INFO [07-05|16:25:29.369] Writing clean trie cache to disk         path=/Users/kimjinkyung/Desktop/dApp_curriculum_inflearn/Blockchain/geth/triecache threads=1
INFO [07-05|16:25:29.373] Regenerated local transaction journal    transactions=0 accounts=0
INFO [07-05|16:25:29.404] Persisted the clean trie cache           path=/Users/kimjinkyung/Desktop/dApp_curriculum_inflearn/Blockchain/geth/triecache elapsed=35.002ms
    그래서 eth.mining으로 현재 채굴중인지 확인해보니 false 뜸. 이건 왜 false..?
    > eth.mining 
    false

    왜 miner.stop()이 null이 뜨는지를 못찾겠음.. 이 링크에서만 같은 현상을 기록해놓음. http://jobtest.digital2u.co.kr/board/form/view/blockchain/865/1/0

    ? miner.start(n) - n개의 스레드에서 채굴을 시작하게 하는 명령어.
    ex) miner.start(2)
    오류 발생 - 'miner.stop()' 입력시 'null'
    해결시도 - 위에서 어떤 연유로 잠시 중지됐던 채굴이 다시 시작됨. 그리고 채굴을 멈춘 적이 없으니 miner.start()가 null이 뜨는 건 당연한 듯.









